### ISSUE TITLE
Notion Search seems not working...... ( it worked for the first few times)

### ISSUE THREAD

**Issue by jerryyang0611** [wrjlewis/notion-search-alfred-workflow#28] opened 2021-03-20 07:13 UTC
**Describe the bug**
I've followed through the process by README.md and filled up my cookie and notionSpaceId, it worked the first few times but didn't work a few days later. ( I didn't change any variables.) (I'm running on macOS Catalina 10.15.6.)

**To Reproduce**
Steps to reproduce the behaviour:
1. Type 'no' and the keyword I wanna search (I've changed the workflow keyword to "no").
2. No result is showing, when I pressed ↵ enter, it didn't show anything
3. Didn't find any error in the debug mode.

**Expected behaviour**
A few days ago, the search result showed properly but a bit slow. However, another day later the searching seems not yet working since then. (I didn't change any variables further.)

**Screenshots**
The searching command: 
<img width="719" alt="Screen Shot 2021-03-20 at 3 05 35 PM" src="https://user-images.githubusercontent.com/45359868/111862062-baa98d00-898d-11eb-847b-a9bcdb3e00fd.png">
My variables: 
<img width="479" alt="Screen Shot 2021-03-20 at 3 06 30 PM" src="https://user-images.githubusercontent.com/45359868/111862088-de6cd300-898d-11eb-8540-b86c426690fc.png">
The debug: (no error) 
![image](https://user-images.githubusercontent.com/45359868/111862542-ef6b1380-8990-11eb-951c-1249dea841a2.png)

**Workflow (please complete the following information):**
 - Version 0.3.3

**Additional context**

**Comment by wrjlewis** [comment] 2021-03-22 18:50
Hey!

Depending on how many pages in your notion workspace, the search api call to notion can be quite slow and take 5-10 seconds to return. 

If it was working before for you, I would try copying the cookie again and pasting it into the respective environment variable. Sometimes you session is reset by Notion and the only solution is to copy the new cookie over, I'm not sure exactly what causes this but it seems to happen very infrequently. 

Please update if that solves it for you.

Thanks

**Comment by jerryyang0611** [comment] 2021-03-23 02:17
Thx so much for the feedback. However, this happened to me pretty much every single day recently. It may be working perfectly fine a day before, but wake up another morning; it doesn't seem to work (even I changed the chrome cookie). 

Is there a waiting time for the notion to load the cookie to let this notion search workflow work when resetting variables?
My notion pages are around 25-30; is this considered "many" pages for the notion API call?  (when it's working, it normally takes 2-3 secs to pop up) so I don't think is this kind of problem. And, sadly, I didn't see any comments on the Alfred forum similar to my situation. :( 

For the "Open URL", do I need to set the URL: to notion://www.notion.so/ if I wanna open in notion app? (doesn't seem to work when I set so..) 

<img width="650" alt="Screen Shot 2021-03-23 at 10 15 54 AM" src="https://user-images.githubusercontent.com/45359868/112082701-c3ce7000-8bc0-11eb-9b76-19c6dd183661.png">

Thanks

**Comment by wrjlewis** [comment] 2021-03-24 18:26
> It may be working perfectly fine a day before, but wake up another morning

Just to check, do you manually log out, or does anyone else log in on the same browser? Just curious because if it sometimes works then clearly the way you are inserting the cookie is correct and it seems that the issue is with Notion invalidating your token; which can be due to a logout action perhaps.

>Is there a waiting time for the notion to load the cookie to let this notion search workflow work when resetting variables?

No there isn't. 

>My notion pages are around 25-30; is this considered "many" pages for the notion API call?

25-30 pages should not cause an above average response, as that is not a large workspace. 

>For the "Open URL", do I need to set the URL: to notion://www.notion.so/ if I wanna open in notion app? (doesn't seem to work when I set so..)

No, you should leave this empty. There is an environment variable built in to this workflow which specifies if you want to open links in the desktop app or a web browser: 'useDesktopClient', I can see you have yours set to true in the previous screenshot you provided

**Comment by wrjlewis** [comment] 2021-04-29 09:43
Hi, others have had success by logging out, logging in, and updating the cookie in the environment valuables. For now I am going to close this issue since there has not been any activity for a while.

**Closed as completed by wrjlewis** 2021-04-29 09:43 UTC
Labels: bug
